# .github/workflows/ci.yml

name: Test
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
env:
  COVERAGE: true
  CODECOV_TOKEN: 3cb5cae8-a986-4734-b7dd-61e9ca84e11b
jobs:
  test-ruby-2-4-x:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4
          bundler-cache: true
      - name: Build and run tests
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake test
  test-ruby-2-5-x:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
          bundler-cache: true
      - name: Build and run tests
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake test
  test-ruby-2-6-x:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - name: Build and run tests
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake test
  test-ruby-2-7-x:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Build and run tests
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake test
  test-ruby-3-0-x:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - name: Build and run tests
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake test